version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/example/browser"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
- package-ecosystem: npm
  directory: "/example/typescript"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
