version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: ws
    versions:
    - 7.4.4
  - dependency-name: typedoc
    versions:
    - 0.20.23
    - 0.20.24
    - 0.20.27
    - 0.20.30
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
- package-ecosystem: npm
  directory: "/example/browser"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: webpack
    versions:
    - 5.18.0
    - 5.19.0
    - 5.20.0
    - 5.20.1
    - 5.20.2
    - 5.21.2
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.28.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: ts-loader
    versions:
    - 8.0.15
    - 8.0.16
    - 9.0.0
    - 9.1.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.2
    - 4.2.3
- package-ecosystem: npm
  directory: "/example/typescript"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.30
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.2.3
