language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  yarn: true
script:
  - yarn run build
  - yarn run test
  - cd example/browser && yarn install && yarn build
  - cd ../../example/javascript && yarn install && yarn build
  - cd ../../example/typescript && yarn install && yarn build
