language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
cache:
  yarn: false
script:
  - yarn run build
  - yarn run test
  - cd example/browser && npm install && npm run build
  - cd ../../example/typescript && npm install && npm run build
