dist: bionic
language: node_js
node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
cache:
  yarn: false
  npm: false
script:
  - yarn run build
  - yarn run test
  - cd example/browser && rm -rf node_modules && npm install && npm run build
  - cd ../../example/typescript && rm -rf node_modules && npm install && npm run build
