name: Test

on:
  push:
    branches:
      - master

    tags:

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Build
        run: |
          yarn run build
      - name: Testing
        run: |
          yarn run test
      - name: Browser example
        working-directory: example/browser
        run: |
          rm -rf node_modules
          npm install
          npm run build
      - name: Browser typescript
        working-directory: example/typescript
        run: |
          rm -rf node_modules
          npm install
          npm run build
